# default config for cal-val-data
# read with config::get(file = "000-config.yml")
default:
  # Salinas + Modesto workbook (datasets: white_salinas_2020, nichols_modesto_2024)
  workbook: 1pXiZUkNP50WXbmAztoEgUJ6rpQNyewmobCuaFHL8UjQ
  data_dir: data
  raw_data_dir: data_raw
