root <- here::here()
read_chr <- function(path) {
  readr::read_csv(path,
                  col_types = readr::cols(.default = readr::col_character()),
                  na = character(), show_col_types = FALSE)
}

test_that("white_salinas_2020 SOC stocks carry the White et al. (2024) correction", {
  obs_path <- file.path(root, "data", "observations.csv")
  skip_if_not(file.exists(obs_path), "observations not generated yet")
  derived <- read_chr(file.path(root, "data_raw", "white_salinas_2020",
                                "soc_stocks_0_30cm_corrected_2024.csv"))
  obs <- read_chr(obs_path)
  obs <- obs[obs$dataset_id == "white_salinas_2020" & obs$variable == "SOC_stock_Mg_ha", ]
  key <- function(d) paste(d$treatment_id, d$replicate_id, d$study_year)

  expect_equal(nrow(derived), 288L)
  expect_equal(nrow(obs), 288L)
  expect_false(anyDuplicated(key(obs)) > 0)
  obs <- obs[match(key(derived), key(obs)), ]
  # the stocks are edited in the workbook and regenerated by ingest, so a value
  # pasted back from the Data in Brief table or a partial re-ingest fails here
  expect_identical(obs$value, derived$SOC_stock_0_30cm_Mg_C_ha)
  expect_identical(obs$attributes_json, derived$attributes_json)
  expect_true(all(obs$fill_status == "SCRIPTED_DERIVED"))
  expect_true(all(obs$method == "equivalent_soil_mass_white_2024_correction"))
  expect_true(all(endsWith(obs$notes, derived$correction_note)))
})
